Grammar simplification
MichaelX-code/calculator pull request #1
Opened 2022-03-23 07:43 UTC by MichaelX-code

2022-03-30 15:18 UTC, hnarkaytis requested changes

2022-03-30 15:18 UTC, hnarkaytis commented on calc.y
> +        yy_scan_string(argv[1]);
Тут передается не вся командная строка, а только первый токен. Т.е. надо передавать все аргументы в кавычках, что не очень удобно.
Хочется тут видеть сборку всей командной строки в одну строку и ее парсинг.

2022-03-30 18:50 UTC, MichaelX-code commented on calc.y
> +        yy_scan_string(argv[1]);
Я хотел изначально так реализовать, но столкнулся с проблемой: что zsh, что bash не будут так просто работать с выражениями, в которых содержится `*`.  Они заменяют её на список файлов в текущей директории.

2022-03-30 19:00 UTC, MichaelX-code commented on calc.y
> +        yy_scan_string(argv[1]);
Можно разве что экранировать все вхождения умножения. Но мне кажется, что кавычки куда логичнее и удобнее ставить.

2022-04-03 14:35 UTC, hnarkaytis approved these changes

2022-04-03 20:17 UTC, merged